FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /build

COPY . .
RUN mvn -pl server -am clean package -DskipTests && \
    cp server/target/app.jar /build/app.jar

FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /build/app.jar app.jar

ENTRYPOINT ["sh","-c","java -jar /app/app.jar --server.port=${PORT:-8080}"]