server.port=8081

spring.profiles.active=dev
spring.messages.encoding=UTF-8

spring.datasource.url=jdbc:postgresql://localhost:5432/verno
spring.datasource.username=verno
spring.datasource.password=verno
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/common,classpath:db/migration/dev

files.storage.root=./data/files
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
spring.servlet.multipart.location=${java.io.tmpdir}

logging.level.ch.verno=DEBUG
logging.level.org.springframework.web=DEBUG

verno.application.run-mode=prod
# MOVE TO ENV!!!
verno.rpc.internal-secret=7AXRdaCuD76hB1jMHvAhejJkI9xZTp/X5KP++SI9fPA=
verno.rpc.url=http://localhost:8081/rpc

verno.api.url=http://localhost:8082
verno.api.username=verno
# MOVE TO ENV!!!
verno.api.password=verno

# MOVE TO ENV!!!
verno.api.resource-access-token-secret=4a7557126d261ee3f0a41f75b3d15a85be58e44b198108280a525bd1d312f5e3

verno.billing.subscription-overview-url=http://localhost:5173
verno.billing.checkout-cancel-url=http://localhost:5173/payment
verno.billing.checkout-success-url=http://localhost:5173/success
verno.billing.portal-return-url=http://localhost:5173/payment

verno.mandant.enabled=true
verno.mandant.header-name=default
verno.mandant.allow-header-fallback=true