server.port=8081

spring.profiles.active=dev
spring.messages.encoding=UTF-8

spring.datasource.url=jdbc:postgresql://localhost:5432/verno
spring.datasource.username=verno
spring.datasource.password=verno
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/common,classpath:db/migration/dev

verno.application.run-mode=dev
# change for deployment and move into ENV
verno.rpc.internal-secret=7AXRdaCuD76hB1jMHvAhejJkI9xZTp/X5KP++SI9fPA=

verno.api.url=http://localhost:8082
verno.api.username=verno
# MOVE TO ENV!!!
verno.api.password=verno

files.storage.root=./data/files
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
spring.servlet.multipart.location=${java.io.tmpdir}

logging.level.ch.verno=DEBUG
logging.level.org.springframework.web=DEBUG