server.port=8082
# use config provider?
verno.rpc.url=http://localhost:8081/rpc
# move into env (and possibly merge both usages)
verno.api.resource-access-token-secret=4a7557126d261ee3f0a41f75b3d15a85be58e44b198108280a525bd1d312f5e3
