-- V1__DB_SCHEMA.sql
-- Clean: Fresh schema only (no legacy columns/backfills, no nested transactions).
-- Target: PostgreSQL

-- =========
-- Core / reference
-- =========
CREATE TABLE IF NOT EXISTS gender
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name        VARCHAR(64),
    description VARCHAR(255)
    );

-- optional unique (global) - keep if you want same gender list shared for all tenants
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uq_gender_name') THEN
ALTER TABLE public.gender ADD CONSTRAINT uq_gender_name UNIQUE (name);
END IF;
END $$;

-- =========
-- Mandants
-- =========
CREATE TABLE IF NOT EXISTS public.mandants
(
    id   BIGINT PRIMARY KEY,
    slug VARCHAR(128) UNIQUE,
    name VARCHAR(128)
    );

-- =========
-- Main tables (all tenant-scoped via mandant_id)
-- =========
CREATE TABLE IF NOT EXISTS address
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    mandant_id   BIGINT NOT NULL DEFAULT 7777,

    street       VARCHAR(128),
    house_number VARCHAR(32),
    zip_code     VARCHAR(16),
    city         VARCHAR(128),
    country      VARCHAR(128),

    CONSTRAINT fk_address_mandant
    FOREIGN KEY (mandant_id) REFERENCES public.mandants (id) ON DELETE RESTRICT
    );

CREATE TABLE IF NOT EXISTS course_level
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    mandant_id    BIGINT NOT NULL DEFAULT 7777,

    code          VARCHAR(32),
    name          VARCHAR(128),
    description   VARCHAR(255),
    sorting_order INT,

    CONSTRAINT fk_course_level_mandant
    FOREIGN KEY (mandant_id) REFERENCES public.mandants (id) ON DELETE RESTRICT
    );

CREATE TABLE IF NOT EXISTS course_schedule
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    mandant_id BIGINT NOT NULL DEFAULT 7777,

    title      VARCHAR(128),

    status     VARCHAR(16) NOT NULL DEFAULT 'PLANNED',
    color      VARCHAR(16) NOT NULL DEFAULT '#55A6F6',

    CONSTRAINT fk_course_schedule_mandant
    FOREIGN KEY (mandant_id) REFERENCES public.mandants (id) ON DELETE RESTRICT,

    CONSTRAINT chk_course_schedule_status
    CHECK (status IN ('PLANNED', 'ACTIVE', 'COMPLETED'))
    );

CREATE TABLE IF NOT EXISTS course_schedule_week
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mandant_id         BIGINT NOT NULL DEFAULT 7777,

    course_schedule_id BIGINT,
    sort_index         INT,
    week               VARCHAR(16), -- e.g. "KW01-2026"

    CONSTRAINT fk_course_schedule_week_mandant
    FOREIGN KEY (mandant_id) REFERENCES public.mandants (id) ON DELETE RESTRICT,

    CONSTRAINT fk_course_schedule_week_schedule
    FOREIGN KEY (course_schedule_id) REFERENCES public.course_schedule (id)
    );

CREATE TABLE IF NOT EXISTS instructor
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    mandant_id BIGINT NOT NULL DEFAULT 7777,

    firstname  VARCHAR(128),
    lastname   VARCHAR(128),
    email      VARCHAR(255),
    phone      VARCHAR(64),
    gender     BIGINT,
    address    BIGINT,

    CONSTRAINT fk_instructor_mandant
    FOREIGN KEY (mandant_id) REFERENCES public.mandants (id) ON DELETE RESTRICT,

    CONSTRAINT fk_instructor_gender
    FOREIGN KEY (gender) REFERENCES public.gender (id),

    CONSTRAINT fk_instructor_address
    FOREIGN KEY (address) REFERENCES public.address (id)
    );

CREATE TABLE IF NOT EXISTS parent
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    mandant_id BIGINT NOT NULL DEFAULT 7777,

    firstname  VARCHAR(128),
    lastname   VARCHAR(128),
    email      VARCHAR(255),
    phone      VARCHAR(64),
    gender     BIGINT,
    address    BIGINT,

    CONSTRAINT fk_parent_mandant
    FOREIGN KEY (mandant_id) REFERENCES public.mandants (id) ON DELETE RESTRICT,

    CONSTRAINT fk_parent_gender
    FOREIGN KEY (gender) REFERENCES public.gender (id),

    CONSTRAINT fk_parent_address
    FOREIGN KEY (address) REFERENCES public.address (id)
    );

CREATE TABLE IF NOT EXISTS course
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    mandant_id         BIGINT NOT NULL DEFAULT 7777,

    title              VARCHAR(128),
    capacity           INT,
    location           VARCHAR(255),
    course_schedule_id BIGINT,
    start_time         TIME,
    end_time           TIME,
    instructor_id      BIGINT,
    note               TEXT,

    CONSTRAINT fk_course_mandant
    FOREIGN KEY (mandant_id) REFERENCES public.mandants (id) ON DELETE RESTRICT,

    CONSTRAINT fk_course_schedule
    FOREIGN KEY (course_schedule_id) REFERENCES public.course_schedule (id),

    CONSTRAINT fk_course_instructor
    FOREIGN KEY (instructor_id) REFERENCES public.instructor (id)
    );

CREATE TABLE IF NOT EXISTS participant
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    mandant_id BIGINT NOT NULL DEFAULT 7777,

    firstname  VARCHAR(128),
    lastname   VARCHAR(128),
    birthdate  DATE,
    gender     BIGINT,
    address    BIGINT,
    email      VARCHAR(255),
    phone      VARCHAR(64),

    parent_one BIGINT,
    parent_two BIGINT,

    note       TEXT,
    active     BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_participant_mandant
    FOREIGN KEY (mandant_id) REFERENCES public.mandants (id) ON DELETE RESTRICT,

    CONSTRAINT fk_participant_gender
    FOREIGN KEY (gender) REFERENCES public.gender (id),

    CONSTRAINT fk_participant_address
    FOREIGN KEY (address) REFERENCES public.address (id),

    CONSTRAINT fk_participant_parent_one
    FOREIGN KEY (parent_one) REFERENCES public.parent (id),

    CONSTRAINT fk_participant_parent_two
    FOREIGN KEY (parent_two) REFERENCES public.parent (id)
    );

-- =========
-- Join tables (tenant-scoped)
-- =========
CREATE TABLE IF NOT EXISTS course_course_level
(
    mandant_id       BIGINT NOT NULL DEFAULT 7777,
    course_id        BIGINT NOT NULL,
    course_level_id  BIGINT NOT NULL,
    sort_index       INT    NOT NULL,

    CONSTRAINT pk_course_course_level PRIMARY KEY (mandant_id, course_id, course_level_id),

    CONSTRAINT fk_ccl_mandant
    FOREIGN KEY (mandant_id) REFERENCES public.mandants (id) ON DELETE RESTRICT,

    CONSTRAINT fk_ccl_course
    FOREIGN KEY (course_id) REFERENCES public.course (id),

    CONSTRAINT fk_ccl_course_level
    FOREIGN KEY (course_level_id) REFERENCES public.course_level (id)
    );

-- If you want ordering unique:
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uk_course_course_level_sort') THEN
ALTER TABLE public.course_course_level
    ADD CONSTRAINT uk_course_course_level_sort UNIQUE (mandant_id, course_id, sort_index);
END IF;
END $$;

CREATE TABLE IF NOT EXISTS course_weekday
(
    mandant_id BIGINT NOT NULL DEFAULT 7777,
    course_id  BIGINT NOT NULL,
    sort_index INT    NOT NULL,
    weekday    VARCHAR(16),

    CONSTRAINT pk_course_weekday PRIMARY KEY (mandant_id, course_id, sort_index),

    CONSTRAINT fk_course_weekday_mandant
    FOREIGN KEY (mandant_id) REFERENCES public.mandants (id) ON DELETE RESTRICT,

    CONSTRAINT fk_course_weekday_course
    FOREIGN KEY (course_id) REFERENCES public.course (id)
    );

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uk_course_weekday_weekday') THEN
ALTER TABLE public.course_weekday
    ADD CONSTRAINT uk_course_weekday_weekday UNIQUE (mandant_id, course_id, weekday);
END IF;
END $$;

CREATE TABLE IF NOT EXISTS participant_course
(
    mandant_id      BIGINT NOT NULL DEFAULT 7777,
    participant_id  BIGINT NOT NULL,
    course_id       BIGINT NOT NULL,

    CONSTRAINT pk_participant_course PRIMARY KEY (mandant_id, participant_id, course_id),

    CONSTRAINT fk_participant_course_mandant
    FOREIGN KEY (mandant_id) REFERENCES public.mandants (id) ON DELETE RESTRICT,

    CONSTRAINT fk_participant_course_participant
    FOREIGN KEY (participant_id) REFERENCES public.participant (id) ON DELETE CASCADE,

    CONSTRAINT fk_participant_course_course
    FOREIGN KEY (course_id) REFERENCES public.course (id)
    );

CREATE TABLE IF NOT EXISTS participant_course_level
(
    mandant_id      BIGINT NOT NULL DEFAULT 7777,
    participant_id  BIGINT NOT NULL,
    course_level_id BIGINT NOT NULL,

    CONSTRAINT pk_participant_course_level PRIMARY KEY (mandant_id, participant_id, course_level_id),

    CONSTRAINT fk_participant_course_level_mandant
    FOREIGN KEY (mandant_id) REFERENCES public.mandants (id) ON DELETE RESTRICT,

    CONSTRAINT fk_participant_course_level_participant
    FOREIGN KEY (participant_id) REFERENCES public.participant (id) ON DELETE CASCADE,

    CONSTRAINT fk_participant_course_level_course_level
    FOREIGN KEY (course_level_id) REFERENCES public.course_level (id)
    );

-- =========
-- Settings tables
-- =========
CREATE TABLE IF NOT EXISTS mandant_settings
(
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    course_weeks_per_schedule        INT     NOT NULL,
    max_participants_per_course      INT     NOT NULL,
    enforce_quantity_settings        BOOLEAN NOT NULL,

    enforce_course_level_settings    BOOLEAN NOT NULL DEFAULT FALSE,
    is_parent_one_main_parent        BOOLEAN DEFAULT TRUE,
    course_report_name               VARCHAR(255) NOT NULL DEFAULT 'course-report-',
    limit_course_assignments_to_active BOOLEAN DEFAULT FALSE
    );

-- =========
-- Security schema
-- =========
CREATE TABLE IF NOT EXISTS app_user
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mandant_id    BIGINT NOT NULL DEFAULT 7777,

    username      VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(255) NOT NULL,

    CONSTRAINT fk_app_user_mandant
    FOREIGN KEY (mandant_id) REFERENCES public.mandants (id) ON DELETE RESTRICT
    );

CREATE TABLE IF NOT EXISTS app_user_settings
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mandant_id   BIGINT NOT NULL DEFAULT 7777,
    user_id      BIGINT NOT NULL,

    theme        VARCHAR(50),
    language_tag VARCHAR(16) NOT NULL DEFAULT 'de',

    CONSTRAINT fk_app_user_settings_mandant
    FOREIGN KEY (mandant_id) REFERENCES public.mandants (id) ON DELETE RESTRICT,

    CONSTRAINT fk_app_user_settings_user
    FOREIGN KEY (user_id) REFERENCES public.app_user (id) ON DELETE CASCADE
    );

-- =========
-- Tenant-scoped uniques (drop old global ones if they exist)
-- =========
ALTER TABLE public.app_user DROP CONSTRAINT IF EXISTS uq_app_user_username;
ALTER TABLE public.course_level DROP CONSTRAINT IF EXISTS uq_course_level_code;
ALTER TABLE public.course_schedule DROP CONSTRAINT IF EXISTS uq_course_schedule_title;
ALTER TABLE public.address DROP CONSTRAINT IF EXISTS uq_address;
ALTER TABLE public.instructor DROP CONSTRAINT IF EXISTS uq_instructor_email;
ALTER TABLE public.parent DROP CONSTRAINT IF EXISTS uq_parent_email;
ALTER TABLE public.participant DROP CONSTRAINT IF EXISTS uq_participant_email;
ALTER TABLE public.course DROP CONSTRAINT IF EXISTS uq_course_title;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uk_app_user_mandant_username') THEN
ALTER TABLE public.app_user
    ADD CONSTRAINT uk_app_user_mandant_username UNIQUE (mandant_id, username);
END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uk_course_level_mandant_code') THEN
ALTER TABLE public.course_level
    ADD CONSTRAINT uk_course_level_mandant_code UNIQUE (mandant_id, code);
END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uk_course_schedule_mandant_title') THEN
ALTER TABLE public.course_schedule
    ADD CONSTRAINT uk_course_schedule_mandant_title UNIQUE (mandant_id, title);
END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uk_course_mandant_title') THEN
ALTER TABLE public.course
    ADD CONSTRAINT uk_course_mandant_title UNIQUE (mandant_id, title);
END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uk_instructor_mandant_email') THEN
ALTER TABLE public.instructor
    ADD CONSTRAINT uk_instructor_mandant_email UNIQUE (mandant_id, email);
END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uk_parent_mandant_email') THEN
ALTER TABLE public.parent
    ADD CONSTRAINT uk_parent_mandant_email UNIQUE (mandant_id, email);
END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uk_participant_mandant_email') THEN
ALTER TABLE public.participant
    ADD CONSTRAINT uk_participant_mandant_email UNIQUE (mandant_id, email);
END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uk_address_mandant_addr') THEN
ALTER TABLE public.address
    ADD CONSTRAINT uk_address_mandant_addr UNIQUE (mandant_id, street, house_number, zip_code, city, country);
END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uk_course_schedule_week_week') THEN
ALTER TABLE public.course_schedule_week
    ADD CONSTRAINT uk_course_schedule_week_week UNIQUE (mandant_id, course_schedule_id, week);
END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uk_course_schedule_week_sort') THEN
ALTER TABLE public.course_schedule_week
    ADD CONSTRAINT uk_course_schedule_week_sort UNIQUE (mandant_id, course_schedule_id, sort_index);
END IF;
END $$;

-- =========
-- Indexes
-- =========
CREATE INDEX IF NOT EXISTS ix_address_mandant ON public.address (mandant_id);
CREATE INDEX IF NOT EXISTS ix_instructor_mandant ON public.instructor (mandant_id);
CREATE INDEX IF NOT EXISTS ix_parent_mandant ON public.parent (mandant_id);
CREATE INDEX IF NOT EXISTS ix_participant_mandant ON public.participant (mandant_id);
CREATE INDEX IF NOT EXISTS ix_course_schedule_mandant ON public.course_schedule (mandant_id);
CREATE INDEX IF NOT EXISTS ix_course_mandant ON public.course (mandant_id);
CREATE INDEX IF NOT EXISTS ix_course_level_mandant ON public.course_level (mandant_id);

CREATE INDEX IF NOT EXISTS ix_csw_schedule ON public.course_schedule_week (mandant_id, course_schedule_id);
CREATE INDEX IF NOT EXISTS ix_course_schedule ON public.course (mandant_id, course_schedule_id);
CREATE INDEX IF NOT EXISTS ix_course_instructor ON public.course (mandant_id, instructor_id);

CREATE INDEX IF NOT EXISTS ix_pc_participant ON public.participant_course (mandant_id, participant_id);
CREATE INDEX IF NOT EXISTS ix_pc_course ON public.participant_course (mandant_id, course_id);

CREATE INDEX IF NOT EXISTS ix_pcl_participant ON public.participant_course_level (mandant_id, participant_id);
CREATE INDEX IF NOT EXISTS ix_pcl_course_level ON public.participant_course_level (mandant_id, course_level_id);

CREATE INDEX IF NOT EXISTS ix_app_user_mandant ON public.app_user (mandant_id);
CREATE INDEX IF NOT EXISTS ix_app_user_settings_mandant ON public.app_user_settings (mandant_id);
CREATE INDEX IF NOT EXISTS ix_app_user_settings_user ON public.app_user_settings (user_id);