ALTER TABLE PUBLIC.PARTICIPANT
DROP CONSTRAINT IF EXISTS UQ_PARTICIPANT_EMAIL;
DROP INDEX IF EXISTS PUBLIC.UQ_PARTICIPANT_EMAIL_INDEX_C;

ALTER TABLE PUBLIC.INSTRUCTOR
DROP CONSTRAINT IF EXISTS UQ_INSTRUCTOR_EMAIL;
DROP INDEX IF EXISTS PUBLIC.UQ_INSTRUCTOR_EMAIL_INDEX_7;