CREATE TABLE IF NOT EXISTS gender
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name        VARCHAR(64) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uq_gender_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS address
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    street       VARCHAR(128) NOT NULL,
    house_number VARCHAR(32)  NOT NULL,
    zip_code     VARCHAR(16)  NOT NULL,
    city         VARCHAR(128) NOT NULL,
    country      VARCHAR(128) NOT NULL,
    CONSTRAINT uq_address UNIQUE (street, house_number, zip_code, city, country)
);

CREATE TABLE IF NOT EXISTS course_level
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    code          VARCHAR(32)  NOT NULL,
    name          VARCHAR(128) NOT NULL,
    description   VARCHAR(255),
    sorting_order INT          NOT NULL,
    CONSTRAINT uq_course_level_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS course_schedule
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title      VARCHAR(128) NOT NULL,
    CONSTRAINT uq_course_schedule_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS course_schedule_week
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_schedule_id BIGINT      NOT NULL,
    sort_index         INT         NOT NULL,
    week               VARCHAR(16) NOT NULL, -- e.g. "KW01-2026"
    CONSTRAINT fk_course_schedule_week_schedule
        FOREIGN KEY (course_schedule_id) REFERENCES course_schedule (id),
    CONSTRAINT uq_course_schedule_week UNIQUE (course_schedule_id, week)
);

CREATE TABLE IF NOT EXISTS instructor
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    firstname  VARCHAR(128) NOT NULL,
    lastname   VARCHAR(128) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    phone      VARCHAR(64),
    gender     BIGINT,
    address    BIGINT,
    CONSTRAINT uq_instructor_email UNIQUE (email),
    CONSTRAINT fk_instructor_gender FOREIGN KEY (gender) REFERENCES gender (id),
    CONSTRAINT fk_instructor_address FOREIGN KEY (address) REFERENCES address (id)
);

CREATE TABLE IF NOT EXISTS parent
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    firstname  VARCHAR(128) NOT NULL,
    lastname   VARCHAR(128) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    phone      VARCHAR(64),
    gender     BIGINT,
    address    BIGINT,
    CONSTRAINT uq_parent_email UNIQUE (email),
    CONSTRAINT fk_parent_gender FOREIGN KEY (gender) REFERENCES gender (id),
    CONSTRAINT fk_parent_address FOREIGN KEY (address) REFERENCES address (id)
);

CREATE TABLE IF NOT EXISTS course
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title              VARCHAR(128) NOT NULL,
    capacity           INT          NOT NULL,
    location           VARCHAR(255),
    course_schedule_id BIGINT,
    start_time         TIME,
    end_time           TIME,
    instructor_id      BIGINT,
    CONSTRAINT uq_course_title UNIQUE (title),
    CONSTRAINT fk_course_schedule FOREIGN KEY (course_schedule_id) REFERENCES course_schedule (id),
    CONSTRAINT fk_course_instructor FOREIGN KEY (instructor_id) REFERENCES instructor (id)
);

CREATE TABLE IF NOT EXISTS course_course_level
(
    course_id       BIGINT NOT NULL,
    course_level_id BIGINT NOT NULL,
    sort_index      INT    NOT NULL,
    CONSTRAINT pk_course_course_level PRIMARY KEY (course_id, course_level_id, sort_index),
    CONSTRAINT fk_ccl_course FOREIGN KEY (course_id) REFERENCES course (id),
    CONSTRAINT fk_ccl_course_level FOREIGN KEY (course_level_id) REFERENCES course_level (id)
);

CREATE TABLE IF NOT EXISTS course_weekday
(
    course_id  BIGINT      NOT NULL,
    sort_index INT         NOT NULL,
    weekday    VARCHAR(16) NOT NULL,
    CONSTRAINT pk_course_weekday PRIMARY KEY (course_id, sort_index),
    CONSTRAINT uq_course_weekday UNIQUE (course_id, weekday),
    CONSTRAINT fk_course_weekday_course FOREIGN KEY (course_id) REFERENCES course (id)
);

CREATE TABLE IF NOT EXISTS participant
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    firstname    VARCHAR(128) NOT NULL,
    lastname     VARCHAR(128) NOT NULL,
    birthdate    DATE,
    gender       BIGINT,
    course_level BIGINT,
    course       BIGINT,
    address      BIGINT,
    email        VARCHAR(255) NOT NULL,
    phone        VARCHAR(64),
    parent_one   BIGINT,
    parent_two   BIGINT,
    CONSTRAINT uq_participant_email UNIQUE (email),
    CONSTRAINT fk_participant_gender FOREIGN KEY (gender) REFERENCES gender (id),
    CONSTRAINT fk_participant_course_level FOREIGN KEY (course_level) REFERENCES course_level (id),
    CONSTRAINT fk_participant_course FOREIGN KEY (course) REFERENCES course (id),
    CONSTRAINT fk_participant_address FOREIGN KEY (address) REFERENCES address (id),
    CONSTRAINT fk_participant_parent_one FOREIGN KEY (parent_one) REFERENCES parent (id),
    CONSTRAINT fk_participant_parent_two FOREIGN KEY (parent_two) REFERENCES parent (id)
);

CREATE TABLE IF NOT EXISTS mandant_settings
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_weeks_per_schedule   INT     NOT NULL,
    max_participants_per_course INT     NOT NULL,
    enforce_quantity_settings   BOOLEAN NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_csw_schedule ON course_schedule_week (course_schedule_id);
CREATE INDEX IF NOT EXISTS idx_course_schedule ON course (course_schedule_id);
CREATE INDEX IF NOT EXISTS idx_course_instructor ON course (instructor_id);
CREATE INDEX IF NOT EXISTS idx_participant_course ON participant (course);
CREATE INDEX IF NOT EXISTS idx_participant_course_level ON participant (course_level);