CREATE TABLE IF NOT EXISTS app_user
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(255) NOT NULL,
    CONSTRAINT uq_app_user_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS app_user_settings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);


