spring.profiles.active=dev
spring.messages.encoding=UTF-8

logging.level.com.vaadin.flow.server=DEBUG
logging.level.com.vaadin.flow.server.communication=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.ch.verno=DEBUG

verno.mandant.enabled=true
verno.mandant.header-name=default
verno.mandant.allow-header-fallback=true
verno.mandant.base-domains=localhost:8080,https://www.verno-app.ch,verno.swiss,localhost

verno.rpc.url=http://localhost:8081/rpc
# change for deployment and move into ENV
verno.rpc.internal-secret=7AXRdaCuD76hB1jMHvAhejJkI9xZTp/X5KP++SI9fPA=

# MOVE TO SERVER AND USE RPC CALL TO GET THEM!!!!!
verno.api.url=http://localhost:8082
verno.api.username=verno
verno.api.password=verno

verno.billing.subscription-overview-url=http://localhost:5173
verno.billing.checkout-cancel-url=http://localhost:5173/payment
verno.billing.checkout-success-url=http://localhost:5173/success
verno.billing.portal-return-url=http://localhost:5173/payment