spring.profiles.active=dev
spring.messages.encoding=UTF-8

logging.level.com.vaadin.flow.server=DEBUG
logging.level.com.vaadin.flow.server.communication=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.ch.verno=DEBUG

verno.rpc.url=http://localhost:8081/rpc

# can be multiple - just seperate them with a comma (,)
verno.ui.loaded-env=RPC_INTERNAL_SECRET