CREATE TABLE IF NOT EXISTS profiles
(
    id         UUID PRIMARY KEY,
    name       VARCHAR(255) NULL,
    created_at TIMESTAMPTZ  NULL DEFAULT now(),
    CONSTRAINT fk_profiles_app_user
        FOREIGN KEY (id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS address
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    street       VARCHAR(255) NULL,
    house_number VARCHAR(64)  NULL,
    zip_code     VARCHAR(32)  NULL,
    city         VARCHAR(255) NULL,
    country      VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS gender
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    name       VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS day_of_week
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    name           VARCHAR(64) NULL,
    sorting_number INT         NULL,
    active         BOOLEAN     NULL     DEFAULT TRUE,
    name_de        VARCHAR(64) NULL,
    name_en        VARCHAR(64) NULL,
    name_fr        VARCHAR(64) NULL
);

CREATE TABLE IF NOT EXISTS course_level
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    code          VARCHAR(64)  NULL,
    name          VARCHAR(255) NULL,
    description   TEXT         NULL,
    sorting_order INT          NULL
);

CREATE TABLE IF NOT EXISTS instructor
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    firstname  VARCHAR(255) NULL,
    lastname   VARCHAR(255) NULL,
    email      VARCHAR(255) NULL,
    phone      VARCHAR(64)  NULL,
    gender     BIGINT       NULL,
    address    BIGINT       NULL,
    CONSTRAINT fk_instructor_gender
        FOREIGN KEY (gender) REFERENCES gender (id) ON DELETE SET NULL,
    CONSTRAINT fk_instructor_address
        FOREIGN KEY (address) REFERENCES address (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS course
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    title        VARCHAR(255) NULL,
    capacity     INT          NULL,
    location     VARCHAR(255) NULL,
    course_level BIGINT       NULL,
    duration     INT          NULL,
    instructor   BIGINT       NULL,
    CONSTRAINT fk_course_course_level
        FOREIGN KEY (course_level) REFERENCES course_level (id) ON DELETE SET NULL,
    CONSTRAINT fk_course_instructor
        FOREIGN KEY (instructor) REFERENCES instructor (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS course_unit
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    course_id        BIGINT      NOT NULL,

    year             INT         NOT NULL,
    calendar_week    INT         NOT NULL CHECK (calendar_week BETWEEN 1 AND 53),

    day_of_week_id   BIGINT      NULL,
    start_time       TIME        NULL,
    duration_minutes INT         NULL CHECK (duration_minutes IS NULL OR duration_minutes > 0),

    CONSTRAINT fk_course_unit_course
        FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE,

    CONSTRAINT fk_course_unit_day_of_week
        FOREIGN KEY (day_of_week_id) REFERENCES day_of_week (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_course_unit_course_id ON course_unit (course_id);
CREATE INDEX IF NOT EXISTS ix_course_unit_year_kw ON course_unit (year, calendar_week);

CREATE TABLE IF NOT EXISTS participant
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    firstname    VARCHAR(255) NULL,
    lastname     VARCHAR(255) NULL,
    birthdate    DATE         NULL,
    gender       BIGINT       NULL,
    course_level BIGINT       NULL,
    course       BIGINT       NULL,
    address      BIGINT       NULL,
    email        VARCHAR(255) NULL,
    phone        VARCHAR(64)  NULL,


    CONSTRAINT fk_participant_gender
        FOREIGN KEY (gender) REFERENCES gender (id) ON DELETE SET NULL,
    CONSTRAINT fk_participant_course_level
        FOREIGN KEY (course_level) REFERENCES course_level (id) ON DELETE SET NULL,
    CONSTRAINT fk_participant_course
        FOREIGN KEY (course) REFERENCES course (id) ON DELETE SET NULL,
    CONSTRAINT fk_participant_address
        FOREIGN KEY (address) REFERENCES address (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS parent
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    firstname  VARCHAR(255) NULL,
    lastname   VARCHAR(255) NULL,
    gender     BIGINT       NULL,
    address    BIGINT       NULL,
    email      VARCHAR(255) NULL,
    phone      VARCHAR(64)  NULL,


    CONSTRAINT fk_parent_gender
        FOREIGN KEY (gender) REFERENCES gender (id) ON DELETE SET NULL,
    CONSTRAINT fk_parent_address
        FOREIGN KEY (address) REFERENCES address (id) ON DELETE SET NULL
);

DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'parent_role') THEN
            CREATE TYPE parent_role AS ENUM ('PARENT_1', 'PARENT_2', 'GUARDIAN');
        END IF;
    END
$$;

CREATE TABLE IF NOT EXISTS participant_parent
(
    participant_id BIGINT      NOT NULL,
    parent_id      BIGINT      NOT NULL,
    role           parent_role NOT NULL DEFAULT 'GUARDIAN',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_participant_parent PRIMARY KEY (participant_id, parent_id),

    CONSTRAINT fk_pp_participant
        FOREIGN KEY (participant_id) REFERENCES participant (id) ON DELETE CASCADE,

    CONSTRAINT fk_pp_parent
        FOREIGN KEY (parent_id) REFERENCES parent (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_pp_participant_parent1
    ON participant_parent (participant_id)
    WHERE role = 'PARENT_1';

CREATE UNIQUE INDEX IF NOT EXISTS ux_pp_participant_parent2
    ON participant_parent (participant_id)
    WHERE role = 'PARENT_2';

CREATE INDEX IF NOT EXISTS ix_pp_parent_id ON participant_parent (parent_id);
CREATE INDEX IF NOT EXISTS ix_pp_participant_id ON participant_parent (participant_id);